definitions:
  handlers.DeleteFileRequest:
    properties:
      filename:
        type: string
    required:
    - filename
    type: object
info:
  contact: {}
  description: A files server
  title: GIN Files API
  version: 1.0.0
paths:
  /delete:
    delete:
      consumes:
      - application/json
      description: Delete a file from the server using the filename provided in the
        JSON body
      parameters:
      - description: API Key
        in: header
        name: X-API-Key
        required: true
        type: string
      - description: Delete file request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.DeleteFileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: File deleted successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body or Filename not provided
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: File not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to delete the file
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a file by filename
      tags:
      - files
  /list-files:
    get:
      description: Retrieves a list of all files in the configured directory.
      parameters:
      - description: API Key
        in: header
        name: X-API-Key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of files
          schema:
            items:
              type: string
            type: array
        "500":
          description: Failed to list files
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List files
      tags:
      - files
  /size:
    get:
      description: Calculates and returns the total size of the folder specified in
        the configuration.
      parameters:
      - description: API Key
        in: header
        name: X-API-Key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Folder size in bytes
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Error message with details
          schema:
            additionalProperties: true
            type: object
      summary: Get folder size
      tags:
      - Files
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a large file to the server
      parameters:
      - description: API Key
        in: header
        name: X-API-Key
        required: true
        type: string
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: File uploaded successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: No file received
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to create upload directory or Failed to save the file
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload a file
      tags:
      - files
swagger: "2.0"
